version: 0.2
env:  
  secrets-manager:
    PRODUCTION_DOMAIN: Secret   
phases:
  install:
    commands:      
      - echo Installing source NPM
      - npm install
  pre_build:
    commands:
      - echo Installing dependencies...     
  build:
    commands:
      - echo Build started...
      - npm run build      
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
  
